# spring.datasource.url=jdbc:mysql://mysql-db:3306/contact_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/contact_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:contact_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:1h}
server.port=8080
server.error.include-message=always
server.error.include-reason=always
server.error.include-binding-errors=always
