#docker
# spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:contact_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# #azure

# spring.datasource.url=jdbc:mysql://contact-app.mysql.database.azure.com:3306/contact_db?useSSL=true&requireSSL=true
# spring.datasource.username=${DB_USER:sqladmin@contact-app}
# spring.datasource.password=${DB_PASSWORD:Umar@23.}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

server.port=${PORT:8080}
server.error.include-message=always
server.error.include-reason=always
server.error.include-binding-errors=always
